// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poke.Infra.Context;

#nullable disable

namespace Poke.Infra.Migrations
{
    [DbContext(typeof(PokeContext))]
    [Migration("20230327053554_001")]
    partial class _001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Poke.Domain.Models.PokemonCaught", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pokemon")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("PokemonMasterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PokemonMasterId");

                    b.ToTable("PokemonCaught");
                });

            modelBuilder.Entity("Poke.Domain.Models.PokemonMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("PokemonMaster");
                });

            modelBuilder.Entity("Poke.Domain.Models.PokemonCaught", b =>
                {
                    b.HasOne("Poke.Domain.Models.PokemonMaster", "PokemonMaster")
                        .WithMany("PokemonCaught")
                        .HasForeignKey("PokemonMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PokemonMaster");
                });

            modelBuilder.Entity("Poke.Domain.Models.PokemonMaster", b =>
                {
                    b.Navigation("PokemonCaught");
                });
#pragma warning restore 612, 618
        }
    }
}
